# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Transforming the Afro-Caribbean World
tagline:          Digital Methods Mini-Site
url:              http://getpoole.com
paginate:         1
baseurl:          http://umd-mith.github.io/taw_workshop/
author:
  name:           Trevor Muñoz
  url:            https://twitter.com/trevormunoz
  email:          tmunoz@umd.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
