# Dependencies
markdown:         redcarpet
highlighter:       pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Transforming the Afro-Caribbean World
tagline:          'Digital Methods Mini-Site'
description:      'Notes on digital sources and methods for a planning workshop discussing a potential large-scale effort to explore Afro-Caribbean labor, migration, and the Panama Canal'
url:              http://umd-mith.github.io/taw_workshop
baseurl:          /taw_workshop/

author:
  name:           'Trevor Muñoz'
  url:            https://twitter.com/trevormunoz

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/umd-mith/taw_workshop
